# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_processor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14node_processor.proto\x12\x0e\x64na.node.proto\"\xbd\x01\n\x15RunNodeProcessRequest\x12\x11\n\x07node_id\x18\x01 \x01(\tH\x00\x12\x13\n\tconf_path\x18\x02 \x01(\tH\x00\x12\x17\n\ncamera_uri\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04sync\x18\x04 \x01(\x08H\x02\x88\x01\x01\x12\x1c\n\x0freport_interval\x18\x05 \x01(\x05H\x03\x88\x01\x01\x42\x06\n\x04\x63onfB\r\n\x0b_camera_uriB\x07\n\x05_syncB\x12\n\x10_report_interval\")\n\x16StopNodeProcessRequest\x12\x0f\n\x07proc_id\x18\x01 \x01(\t\"\x1b\n\rStartedStatus\x12\n\n\x02ts\x18\x01 \x01(\x03\"0\n\rRunningStatus\x12\x13\n\x0b\x66rame_index\x18\x01 \x01(\x03\x12\n\n\x02ts\x18\x02 \x01(\x03\"\x1b\n\rStoppedStatus\x12\n\n\x02ts\x18\x01 \x01(\x03\"\xe8\x01\n\x0cStatusReport\x12\x0f\n\x07proc_id\x18\x01 \x01(\t\x12&\n\x06status\x18\x02 \x01(\x0e\x32\x16.dna.node.proto.Status\x12\x30\n\x07started\x18\x03 \x01(\x0b\x32\x1d.dna.node.proto.StartedStatusH\x00\x12\x30\n\x07running\x18\x04 \x01(\x0b\x32\x1d.dna.node.proto.RunningStatusH\x00\x12\x30\n\x07stopped\x18\x05 \x01(\x0b\x32\x1d.dna.node.proto.StoppedStatusH\x00\x42\t\n\x07\x64\x65tails*=\n\x06Status\x12\x0b\n\x07STARTED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\x0c\n\x08\x46INISHED\x10\x02\x12\x0b\n\x07STOPPED\x10\x03\x32\xaf\x01\n\rNodeProcessor\x12N\n\x03Run\x12%.dna.node.proto.RunNodeProcessRequest\x1a\x1c.dna.node.proto.StatusReport\"\x00\x30\x01\x12N\n\x04Stop\x12&.dna.node.proto.StopNodeProcessRequest\x1a\x1c.dna.node.proto.StatusReport\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_processor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=618
  _STATUS._serialized_end=679
  _RUNNODEPROCESSREQUEST._serialized_start=41
  _RUNNODEPROCESSREQUEST._serialized_end=230
  _STOPNODEPROCESSREQUEST._serialized_start=232
  _STOPNODEPROCESSREQUEST._serialized_end=273
  _STARTEDSTATUS._serialized_start=275
  _STARTEDSTATUS._serialized_end=302
  _RUNNINGSTATUS._serialized_start=304
  _RUNNINGSTATUS._serialized_end=352
  _STOPPEDSTATUS._serialized_start=354
  _STOPPEDSTATUS._serialized_end=381
  _STATUSREPORT._serialized_start=384
  _STATUSREPORT._serialized_end=616
  _NODEPROCESSOR._serialized_start=682
  _NODEPROCESSOR._serialized_end=857
# @@protoc_insertion_point(module_scope)
