# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reid_metrics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12reid_metrics.proto\x12\x0e\x64na.node.proto\"}\n\x11TrackFeatureProto\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x10\n\x08track_id\x18\x02 \x01(\t\x12\x15\n\x08\x62\x66\x65\x61ture\x18\x03 \x01(\x0cH\x00\x88\x01\x01\x12\x15\n\rzone_relation\x18\x04 \x01(\t\x12\n\n\x02ts\x18\x05 \x01(\x03\x42\x0b\n\t_bfeatureb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reid_metrics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TRACKFEATUREPROTO']._serialized_start=38
  _globals['_TRACKFEATUREPROTO']._serialized_end=163
# @@protoc_insertion_point(module_scope)
